apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
  namespace: trend-app
  labels:
    app: trend-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0264ab9b0856599d7,subnet-0d0a9483cc393bc3b"
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
